### ISSUE TITLE
TypeError: api_1.getSpan is not a function

### ISSUE THREAD

**Issue by spirrello** [aws-observability/aws-otel-js#57]
Hi,

I followed the docs for the sample app and I'm getting the following error whenever I curl or browse to any of the endpoints.  Can you please help?

Using Node **v14.17.3.**

```
Node HTTP listening on 0.0.0.0:8080
/Users/xxxxx/code/aws-otel-js/sample-apps/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:368
        const currentSpan = api_1.getSpan(ctx);
                                  ^

TypeError: api_1.getSpan is not a function
    at HttpInstrumentation._startHttpSpan (/Users/xxxxx/code/aws-otel-js/sample-apps/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:368:35)
    at Server.incomingRequest (/Users/xxxxx/code/aws-otel-js/sample-apps/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:259:42)
    at parserOnIncoming (_http_server.js:897:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    
```

**Comment by NathanielRN** [comment]
Hi @spirrello ! Thanks for raising this issue 😄

I ran into the problem you're seeing here last week when I was updating our sample app example. You can see [in this PR 7 days ago](https://github.com/aws-observability/aws-otel-js/pull/58/files#diff-01a4ccf76120ed5e93f695f54327ef1ddff6c7f870d2bdc3798e4f33db01eef6R69) I had to update our `server.js` example to follow the latest changes from upstream `opentelemetry-js` which changed `api.getSpan()` to -> `api.trace.getSpan()`.

However I noticed from your trace logs that the error is coming from `node_modules/@opentelemetry/instrumentation-http`. I think it's possible that you are using our recently updated `aws-otel-js` app which is built for `opentelemetry-js@0.23.0` with an older version of `opentelemetry-js` (possibly `0.19.0` because that's what it was targetting 7 days ago!)

If you download the latest sample app you should see that the dependencies have been updated to be `0.23.0` across all packages, including `@opentelemetry/instrumentation-http`:

https://github.com/aws-observability/aws-otel-js/blob/5d0eccce7731924db784b883d25c3d7d9fa96c9d/sample-apps/package.json#L19-L30

Could you try following [these steps in the README.md](https://github.com/aws-observability/aws-otel-js/blob/main/sample-apps/README.md#getting-started) and let me know if you can successfully curl the endpoints?

Let me know if I can clarify anything!

**Comment by spirrello** [comment]
@NathanielRN Thanks for the response.  I will try this later this week and will let you know how it goes.

**Comment by spirrello** [comment]
[**@NathanielRN**](https://github.com/NathanielRN) that worked.  Thanks again!
