### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by shidaying** [aws-observability/aws-otel-js#77]
I am a newcomer to AWS. For the example of send-metric-app.js, I can't find the corresponding aws-otel-js-sample namespace on Cloudwatch Metrics, so I don't know where the data is uploaded

I have setted ~/.aws(config&credentials) in my locale and run it with `node send-metric-app.js`

Can someone tell me what I should do to report metric and Log data to CloudWatch,

code in below
```
'use strict';

// OTel JS - API

const { CollectorMetricExporter } = require('@opentelemetry/exporter-collector-grpc');
const { MeterProvider } = require('@opentelemetry/sdk-metrics-base');
const { Resource } = require('@opentelemetry/resources');
const { SemanticResourceAttributes } = require('@opentelemetry/semantic-conventions')

/** The OTLP Metrics Provider with OTLP gRPC Metric Exporter and Metrics collection Interval  */
const meter = new MeterProvider({
  resource: Resource.default().merge(new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: "aws-otel-js-sample",
    [SemanticResourceAttributes.CLOUD_REGION]: "ap-southeast-1",
    [SemanticResourceAttributes.AWS_LOG_GROUP_NAMES]: "/aws/metric/test",
    [SemanticResourceAttributes.AWS_LOG_STREAM_NAMES]: "open-telemetry"
  })),
  // Expects Collector at env variable `OTEL_EXPORTER_OTLP_ENDPOINT`, otherwise, http://localhost:4317
  exporter: new CollectorMetricExporter(),
  interval: 1000,
}).getMeter('aws-otel-js');

/** Counter Metrics */
const payloadMetric = meter.createCounter('payload', {
  description: 'Metric for counting request payload size',
});

/** Up and Down Counter Metrics */
const activeReqMetric = meter.createUpDownCounter('activeRequest', {
  description: 'Metric for record active requests',
});

/** Value Recorder Metrics with Histogram */
const requestLatency = meter.createValueRecorder('latency', {
  description: 'Metric for record request latency',
});

/** Define Metrics Dimensions */
const labels = { pid: process.pid, env: 'beta' };

/** Send the defined metrics every seconds */
setInterval(() => {
  payloadMetric.bind(labels).add(1);
  activeReqMetric.bind(labels).add(Math.random() > 0.5 ? 1 : -1);
  requestLatency.bind(labels).record(Math.random() * 1000)
}, 1000);

```

in origin code new Resource({[ResourceAttributes.SERVICE_NAME]: "aws-otel-js-sample"}), but ResourceAttributes is not enum, i don‘t know what's the name when i should set the namespace or log group, so i change it to SemanticResourceAttributes

**Comment by NathanielRN** [comment]
Hey @shidaying! Thanks for asking your question 🙂

I was able to see metrics in my CloudWatch console on AWS, so I'll explain what I did.

First you want to [run the sample app we have on this repository](https://github.com/aws-observability/aws-otel-js/tree/main/sample-apps) (but you already found this): 

```bash
cd aws-otel-js/sample-apps && LISTEN_ADDRESS=localhost:8080 node server.js
```

Next, we need to have a collector running. There are a couple of ways to do this, but this is a _crucial step_ because this is what exports metrics and traces to AWS X-Ray. The collector always needs a configuration. You can use [the one we provide in this repo](https://github.com/aws-observability/aws-otel-js/blob/74f3c6e5ee2133451722991cf7c360a888e8b555/.github/collector/collector-config.yml#L1). So first `cd .github/collector` and then start the collector as follows:

```bash
docker run -v $HOME/.aws:/.aws \
           -v $(pwd)/:/config \
           otel/opentelemetry-collector-contrib:latest --config /config/collector-config.yml
```

Finally, we can generate metrics by running `curl localhost:8080/outgoing-http-call` to hit the endpoint of our app which produces metrics.

Doing this, I was able to see metrics, but I'll explain why I expect it to work.

You can see in our configuration for the collector the following:

https://github.com/aws-observability/aws-otel-js/blob/74f3c6e5ee2133451722991cf7c360a888e8b555/.github/collector/collector-config.yml#L12-L13

The [`awsemfexporter` is the exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter) used to export metrics from OTel so that they show up in Cloudwatch.

From [the documentation of the exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter#exporter-configuration), we can see that because our configuration doesn't set much of anything, it will use the defaults. This means the following:

```
log_group_name = "/metrics/default"
log_stream_name = "otel-stream"
namespace = "default"
```

_However_, we do set one things, that is that we set the `SERVICE_NAME` to be `aws-otel-integ-test` (as you pointed out in the issue:

https://github.com/aws-observability/aws-otel-js/blob/74f3c6e5ee2133451722991cf7c360a888e8b555/sample-apps/create-a-meter.js#L11

Because we are using the `awsemf` exporter, we actual expect the following values to show up in AWS CloudWatch > Log Groups:

```
log_group_name = "/metrics/aws-otel-integ-test"
log_stream_name = "otel-stream-{uuid}"
namespace = "aws-otel-integ-test"
```

You can see this in my AWS account like so:

![image](https://user-images.githubusercontent.com/23139455/142467048-21a42365-42ba-48f5-850c-c341901f773c.png)

If you click on "All metrics" you should also see the generated metrics under the `aws-otel-integ-test` namespace, again because we set that in the `create-a-meter.js` file of our Node App.

Hopefully that helps answer your question, please let me know if I can clarify anything! 🙂

**Comment by NathanielRN** [comment]
Hi @shidaying , were you able to resolve your issue?
